version: '2.1'
services:
  wireguard: 
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1014
      - PGID=1015
      - TZ=Etc/UTC
      - SERVERURL=srx.gasser.blue
      - SERVERPORT=51820
      - PEERS=30
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.1.2.0
      - ALLOWEDIPS=0.0.0.0/0
      - PERSISTENTKEEPALIVE_PEERS=
      - LOG_CONFS=true
    ports:
      - '51820:51820/udp'
    volumes:
      - ./wireguard_data:/config
      - /lib/modules:/lib/modules
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    restart: unless-stopped
    networks:
      customnetwork:
        ipv4_address: 10.1.1.2

  netcat:
    build: 
      context: vulhub_files
      dockerfile: ../Dockerfile.nc
    networks:
      customnetwork:
        ipv4_address: 10.1.1.3
      hiddennetwork:
        ipv4_address: 10.1.2.2

  passwords:
    image: lipanski/docker-static-website:latest
    volumes:
      - ./passwords.html:/home/static/index.html
    networks:
      hiddennetwork:
        ipv4_address: 10.1.2.173
    command: /busybox httpd -f -v -p 80 -c httpd.conf

  web:
    image: vulhub/appweb:7.0.1
    volumes:
      - ./vulhub_files/appweb.conf:/etc/appweb/appweb.conf
    networks:
      customnetwork:
        ipv4_address: 10.1.1.4

  couchdb:
    image: vulhub/couchdb:3.2.1
    ports:
      - "5984"
      - "4369"
      - "9100"
    environment:
      COUCHDB_USER: vulhub
      COUCHDB_PASSWORD: vulhub
    networks:
      customnetwork:
        ipv4_address: 10.1.1.5

  huge:
    build: 
      context: vulhub_files
      dockerfile: ../Dockerfile.huge
    networks:
      customnetwork:
        ipv4_address: 10.1.1.10

  dns:
    image: vulhub/bind:latest
    ports:
     - "53"
    volumes:
     - ./vulhub_files/dns/named.conf.local:/etc/bind/named.conf.local
     - ./vulhub_files/dns/vulhub.db:/etc/bind/vulhub.db
    networks:
      customnetwork:
        ipv4_address: 10.1.1.11

  grafana:
    image: vulhub/grafana:8.2.6
    ports:
      - "3000"
    networks:
      customnetwork:
        ipv4_address: 10.1.1.12

  jenkins:
    image: vulhub/jenkins:2.138
    ports:
      - "50000"
      - "8080"
    init: true
    networks:
      customnetwork:
        ipv4_address: 10.1.1.14

  jupyter:
    image: vulhub/jupyter-notebook:5.2.2
    command: start-notebook.sh --NotebookApp.token=''
    ports:
     - "8888"
    networks:
       customnetwork:
         ipv4_address: 10.1.1.20
        
  sshd:
    image: vulhub/libssh:0.8.1
    ports:
     - "2222"
    networks:
       customnetwork:
         ipv4_address: 10.1.1.21

  solr:
    image: vulhub/solr:8.11.0
    ports:
     - "8983"
    networks:
       customnetwork:
         ipv4_address: 10.1.1.22

  mysql:
    image: vulhub/mysql:5.5.23
    ports:
     - "3306"
    networks:
       customnetwork:
         ipv4_address: 10.1.1.23

networks:
  customnetwork:
    ipam:
      config:
        - subnet: 10.1.1.0/24
  hiddennetwork:
    ipam:
      config:
        - subnet: 10.1.2.0/24
