FROM ubuntu:22.04

RUN apt update
RUN apt install -y apache2 dnsmasq samba openssh-server mysql-server cups
RUN sed -i -e s/localhost:631/631/ /etc/cups/cupsd.conf
RUN sed -i -e "s/# port/port/" /etc/mysql/mysql.conf.d/mysqld.cnf
RUN sed -i -e "s/127.0.0.1/0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf
COPY start_huge.sh /root

CMD /root/start_huge.sh
